version: "3.7"

services:
  db:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_USER: mmuser
      POSTGRES_PASSWORD: mmuser_password
      POSTGRES_DB: mattermost
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    networks:
      - mattermost-network

  app:
    image: mattermost/mattermost-team-edition:latest
    restart: unless-stopped
    ports:
      - "8065:8065"
    environment:
      - MM_CONFIG=/mattermost/config/config.json
      - MM_USERNAME=admin
      - MM_PASSWORD=adminpassword
      - MM_DB_HOST=db
      - MM_DB_PORT=5432
      - MM_DB_USER=mmuser
      - MM_DB_PASSWORD=mmuser_password
      - MM_DB_NAME=mattermost
    volumes:
      - ./volumes/app/mattermost:/mattermost/data
    depends_on:
      - db
    networks:
      - mattermost-network

networks:
  mattermost-network:
