version: "3"

services:
  app:
    container_name: mattermost
    image: mattermost/mattermost-team-edition:latest
    restart: unless-stopped
    volumes:
      - ./mattermost/config:/mattermost/config:rw
      - ./mattermost/data:/mattermost/data:rw
      - ./mattermost/logs:/mattermost/logs:rw
      - ./mattermost/plugins:/mattermost/plugins:rw
      - ./mattermost/client/plugins:/mattermost/client/plugins:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MM_USERNAME=user
      - MM_PASSWORD=password
      - MM_DBNAME=testdb
      - MM_SQLSETTINGS_DATASOURCE=postgres://user:password@172.17.0.1:5432/testdb?sslmode=disable&connect_timeout=10
