version: "3.8"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "P@ssw0rd123!"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - services

  mssql_exporter:
    image: gocodify/mssql_exporter:latest
    container_name: mssql-exporter
    platform: linux/arm64 # ARM64 플랫폼 에뮬레이션
    environment:
      DATA_SOURCE_NAME: "sqlserver://sa:P@ssw0rd123!@mssql:1433?database=master"
    ports:
      - "4000:9090"
    depends_on:
      - mssql
    networks:
      - services

volumes:
  mssql_data:

networks:
  services:
    external: true
