version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - service

  postgres_exporter:
    image: wrouesnel/postgres_exporter:latest
    container_name: postgres-exporter
    environment:
      DATA_SOURCE_NAME: postgresql://user:password@postgres:5432/testdb?sslmode=disable
    ports:
      - "9187:9187"
    depends_on:
      - postgres
    networks:
      - service

volumes:
  postgres_data:

networks:
  service:
