version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - services # 외부 네트워크 사용

  mongodb_exporter:
    image: bitnami/mongodb-exporter:latest
    container_name: mongodb-exporter
    environment:
      MONGODB_URI: mongodb://root:root@mongo:27017
    ports:
      - "9216:9216"
    depends_on:
      - mongo
    networks:
      - services # 외부 네트워크 사용

volumes:
  mongo_data:

networks:
  services:
    external: true # 외부 네트워크 사용
