version: "3.7"
services:
  web:
    image: "gitlab/gitlab-ce:latest"
    restart: always
    ports:
      - "8080:80"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8080'
