version: "3"
services:
  redmine:
    container_name: redmine
    image: redmine
    restart: always
    ports:
      - "3080:3000"
    environment:
      REDMINE_DB_MYSQL: redmineDB
      REDMINE_DB_PASSWORD: "redmine"
      REDMINE_DATABASE: redmine
      REDMINE_DB_ENCODING: utf8
    volumes:
      - ./files:/usr/src/redmine/files
      - ./plugins:/usr/src/redmine/plugins
      - ./themes:/usr/src/redmine/public/themes
  redmineDB:
    container_name: mysqlDC
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "redmine"
      MYSQL_DATABASE: redmine
    volumes:
      - ./mysql:/var/lib/mysql
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
