version: "3.7"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=172.17.0.1
      - DB_PORT=5432
      - DB_DATABASE=testdb
      - DB_USER=user
      - DB_PASSWORD=password
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=adminpassword
      - KC_HOSTNAME=https://keycloak.smartseo.kr # HTTPS로 설정
      - KC_HOSTNAME_STRICT=true # 리버스 프록시가 있는 경우 HTTPS를 강제하도록 설정
    ports:
      - "8084:8080"
    command:
      - start-dev
    volumes:
      - keycloak-data:/opt/keycloak/data

  # postgres:
  #   image: postgres:14
  #   environment:
  #     - POSTGRES_DB=keycloak
  #     - POSTGRES_USER=keycloak
  #     - POSTGRES_PASSWORD=keycloakpassword
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data

volumes:
  keycloak-data:
  # postgres-data:
