version: "3"

services:
  strapi:
    build: .
    container_name: strapi
    ports:
      - "1337:1337"
    volumes:
      - .:/opt/app
    environment:
      - NODE_ENV=development
    command: yarn develop
    # 권한 문제 해결을 위한 사용자 설정
    user: "0:0" # 현재 디렉토리 소유자의 UID와 GID로 실행
    working_dir: /opt/app

    # 권한 문제 방지를 위한 초기 설정 명령어
    init: true
    entrypoint:
      [
        "/bin/sh",
        "-c",
        "mkdir -p /opt/app/.strapi && chown -R 0:0 /opt/app/ && yarn develop",
      ]

    # 재시작 정책
    restart: always

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:1337 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
