version: "3"

services:
  strapi:
    build: .
    container_name: strapi
    ports:
      - "1337:1337"
    environment:
      - NODE_ENV=development
    command: yarn develop
    # 권한 문제를 방지하기 위한 사용자 설정
    user: "node"

    # 재시작 정책 설정 (필요에 따라 추가)
    restart: always
